<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>jxlab</artifactId>
        <groupId>com.mhschmieder</groupId>
        <version>1.0.0</version>
    </parent>

	<modelVersion>4.0.0</modelVersion>

    <artifactId>fxchart</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>fxchart</name>
	<url>https://github.com/mhschmieder/fxchart</url>
	<description>Utilities and custom classes for JavaFX based Charting work.</description>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://opensource.org/licenses/MIT</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<url>https://github.com/mhschmieder/fxchart</url>
		<connection>scm:git:git://github.com/mhschmieder/fxchart.git</connection>
		<developerConnection>scm:git:git@github.com:mhschmieder/fxchart.git</developerConnection>
	</scm>

	<developers>
		<developer>
			<email>markhschmieder@gmail.com</email>
			<name>Mark Schmieder</name>
			<url>https://github.com/mhschmieder</url>
		</developer>
        <developer>
            <email>brandon-t-harvey@pm.me</email>
            <name>Brandon Harvey</name>
            <url>https://github.com/brandon-t-harvey</url>
        </developer>
	</developers>

	<dependencies>
		<dependency>
			<groupId>com.mhschmieder</groupId>
			<artifactId>jcommons</artifactId>
			<version>1.0.1</version>
		</dependency>
        <dependency>
            <groupId>com.mhschmieder</groupId>
            <artifactId>jphysics</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.mhschmieder</groupId>
            <artifactId>jchart</artifactId>
            <version>1.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.mhschmieder</groupId>
            <artifactId>fxcontrols</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>25.0.1</version>
        </dependency>
    </dependencies>


</project>
